Document: qneptunea-plugin-shindanmaker
Title: Debian qneptunea-plugin-shindanmaker Manual
Author: <insert document author here>
Abstract: This manual describes what qneptunea-plugin-shindanmaker is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qneptunea-plugin-shindanmaker/qneptunea-plugin-shindanmaker.sgml.gz

Format: postscript
Files: /usr/share/doc/qneptunea-plugin-shindanmaker/qneptunea-plugin-shindanmaker.ps.gz

Format: text
Files: /usr/share/doc/qneptunea-plugin-shindanmaker/qneptunea-plugin-shindanmaker.text.gz

Format: HTML
Index: /usr/share/doc/qneptunea-plugin-shindanmaker/html/index.html
Files: /usr/share/doc/qneptunea-plugin-shindanmaker/html/*.html


